import ast
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = PROJECT_ROOT / "src" / "bvar"
API_DOC = PROJECT_ROOT / "docs" / "api.md"

PUBLIC_NAMESPACES = (
    ("Core API", "bvar", PACKAGE_ROOT / "__init__.py"),
    ("Forecasting", "bvar.forecast", PACKAGE_ROOT / "forecast" / "__init__.py"),
    ("Models", "bvar.models", PACKAGE_ROOT / "models" / "__init__.py"),
    ("Plotting", "bvar.plots", PACKAGE_ROOT / "plots" / "__init__.py"),
)


def read_exports(path: Path) -> list[str]:
    """Read a module's literal ``__all__`` declaration without importing it."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in targets
        ):
            exports = ast.literal_eval(node.value)
            if not isinstance(exports, list) or not all(
                isinstance(name, str) for name in exports
            ):
                raise ValueError(f"{path}: __all__ must be a literal list of strings")
            return exports
    raise ValueError(f"{path}: no literal __all__ declaration found")


def public_objects() -> list[tuple[str, list[str]]]:
    """Return public object paths grouped by documentation section."""
    namespace_exports = [
        (section, namespace, read_exports(path))
        for section, namespace, path in PUBLIC_NAMESPACES
    ]
    child_exports = {
        name
        for _, namespace, exports in namespace_exports
        if namespace != "bvar"
        for name in exports
    }

    sections = []
    for section, namespace, exports in namespace_exports:
        if namespace == "bvar":
            exports = [name for name in exports if name not in child_exports]
        sections.append((section, [f"{namespace}.{name}" for name in exports]))
    return sections


def render_api_page(sections: list[tuple[str, list[str]]]) -> str:
    """Render the Markdown manifest consumed by mkdocstrings."""
    lines = [
        "# API Reference",
        "",
        (
            "This file is generated by `scripts/generate_api_docs.py` from the package's `__all__` declarations. "
            "The API content is rendered from the current source during each Zensical build."
        ),
        "",
    ]
    for section, objects in sections:
        lines.extend((f"## {section}", ""))
        for object_path in objects:
            lines.extend((f"::: {object_path}", ""))
    return "\n".join(lines)


def main() -> None:
    """Update the generated API documentation manifest."""
    API_DOC.write_text(render_api_page(public_objects()), encoding="utf-8")


if __name__ == "__main__":
    main()
